name: Update Manifest and Commit Changes

on:
  workflow_dispatch:
  push:

jobs:
  update-manifest:
    name: "Update Manifest and Commit Changes"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: ubiquity-os/action-deploy-plugin@main
        with:
          treatAsEsm: false
          sourcemap: false
          pluginEntry: "${{ github.workspace }}/src/main.ts"
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
